#!/bin/sh

# build du front
cd frontend-react/
yarn build

# synchro du back local -> server
cd ../symfony/
rsync -av -e 'ssh -p 5022' ./ ghugkvrz@node6-fr.n0c.com:~/symfony --include=public/.htaccess --exclude-from=.gitignore --exclude=".*"

# install des dépendances back
ssh ghugkvrz@node6-fr.n0c.com -p 5022 'cd symfony/ && php composer.phar install --no-dev --optimize-autoloader && php bin/console cache:clear'

cd ..

# suppression du fichier build puis copie local -> server
ssh ghugkvrz@node6-fr.n0c.com -p 5022 'rm -r build/* && echo ----File build/ empty----'
scp -P 5022 -r frontend-react/build/* ghugkvrz@node6-fr.n0c.com:build/
