version: '3.8'

services:
    symfony:
        container_name: symfony
        build:
            context: ./symfony/.
            target: symfony
        ports:
            - 8000:80
        entrypoint: ["tail", "-f", "/dev/null"]
        environment:
            APP_ENV: test
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: pbourdet
