version: '3.8'

services:
    symfony:
        container_name: symfony
        image: pbourdet/symfony-dev
        build:
            context: ./symfony/.
            target: symfony_dev
        depends_on:
            mysql:
                condition: service_started
        ports:
            - 8000:80
        volumes:
            - ./symfony/:/app
            - ./symfony/docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            APP_ENV: dev
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: pbourdet
    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        logging:
            driver: 'none'  #disable saving logs
        ports:
            - 1025:1025
            - 8025:8025
    mercure:
        container_name: mercure
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':4000'
            MERCURE_PUBLISHER_JWT_KEY: '1234'
            MERCURE_SUBSCRIBER_JWT_KEY: '1234'
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "4000:4000"
    react:
        container_name: react
        image: pbourdet/react-dev
        build:
            context: ./frontend-react/.
            target: react
            args:
                APP_ENV: dev
        volumes:
            - /app/node_modules
            - ./frontend-react/:/app
        ports:
            - 3000:3000
