version: '3.8'

services:
    symfony:
        container_name: symfony
        build:
            context: ./symfony/.
            target: symfony
        ports:
            - 8000:80
        entrypoint: ["tail", "-f", "/dev/null"]
        environment:
            APP_ENV: test
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: pbourdet
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        logging:
            driver: 'none'  #disable saving logs
        ports:
            - 1025:1025
            - 8025:8025
    react:
        container_name: react
        build:
            context: ./frontend-react/.
            target: react
            args:
                APP_ENV: dev
        ports:
            - 3000:3000
        entrypoint: ["tail", "-f", "/dev/null"]
