version: '3.8'

services:
    symfony:
        container_name: symfony
        build:
            context: ./symfony/.
            target: symfony_php
        ports:
            - 8000:80
        entrypoint: ["tail", "-f", "/dev/null"]
        environment:
            APP_ENV: test
    postgres:
        image: postgres:13-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: pbourdet
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
